version: '3.7'

services:
  web:
    build: .
    image: uzman
    container_name: test_deploy_web
    command: gunicorn presto_shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./presto_shop_project:/app/
      - staticfiles:/app/static/
      - media:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      



  db:
    image: postgres
    container_name: test_deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=presto
      - POSTGRES_USER=presto
      - POSTGRES_PASSWORD=zdraco1Cak
 
    
    

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - staticfiles:/app/static/
      - media:/app/media
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
  media: